### ISSUE TITLE
c2m2 added fence AI pathing

### ISSUE THREAD

**Issue by SirPlease** [Derpduck/L4D2-Comp-Stripper-Rework#2]
Infected AI will just get stuck on the added fence.
https://steamuserimages-a.akamaihd.net/ugc/1667986590230305020/94C90D6DB3097C5D22193001949ABAEDD636A167/

**Comment by Derpduck** [comment]
Fixing nav issues will come at a later stage all in one go, unless it creates an actual jesus spot for survivors it's low priority.
For now I think its acceptable to fix this later since the current configs also do not fix nav issues like this, and because AI infected are fairly uncommon in competitive.

**Comment by Derpduck** [comment]
Due to the layout of the nav mesh I'm not sure how fixable this is without redesigning it
![](https://i.imgur.com/aUS7tRq.jpg)
